### ISSUE TITLE
Can you make it for The Division?

### ISSUE THREAD

**Issue by systemsiteseason** [dtzxporter/avatar-modloader#1]
i find the same function with pattern "40 53 55 41 56 48 81 EC ? ? ? ? 41 8B E8 4C 8B F2 48 8B D9 48 85 D2"  of the division. but i can't make it jump to function hk_open_file_stream. Can you do that?

**Comment by dtzxporter** [comment]
I will not support any games with anti-cheat. If you want that you'll have to do it yourself.
