### ISSUE TITLE
Star Wars Outlaws Support

### ISSUE THREAD

**Issue by michalss** [dtzxporter/avatar-modloader#2]
Hi,

Can you please add support for this game ? Star Wars Outlaws Support.
Gonna do localization only.

Thank you

**Comment by dtzxporter** [comment]
Hi!

I'm not really interested in updating this project long term, I made a branch with an updated pattern for the hook function (untested), you can get the release here: https://github.com/dtzxporter/avatar-modloader/releases/tag/v1.00-untested

based on the `outlaws-modloader` branch.
